In [105]:
import pandas
import re
import math

dRaw = pandas.read_csv("./KA_DATA/ALGORITHMS_TSIMANE_newAlgo_format.csv")

outputCSVHeaders = ['AGE', 'ALGOTYPE', 'DEMO', 'OVERALL.RESPONSE', 'KNOWERLEV','GENDER', 'ID','PASS_SORT','PASS_DOUBLE','PASS_HITCH','PASS_SORT_1','PASS_DOUBLE_1','PASS_HITCH_1', 'OVERALL.RESPONSE.NO', 'RESPONSE.NO', 'ACTION.NO', 'BUCKET', 'RESPONSE']

In [106]:
dRaw.head()

,ID,DOB,AGE,ALGO TYPE,DEMO,OUTPUT,OUTPUT_SIDE,OUTPUT.1,OUTPUT_SIDE.1,OUTPUT.2,...,OUTPUT.18,OUTPUT_SIDE.18,OUTPUT.19,OUTPUT_SIDE.19,OUTPUT.20,OUTPUT_SIDE.20,OUTPUT.21,OUTPUT_SIDE.21,NUMBER_MOVEMENTS,NOTES
0,74.0,NaN,12.0,sort,NaN,red,left,blue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
1,74.0,NaN,12.0,double,NaN,red,left,blue,right,redred,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN
2,74.0,NaN,12.0,hitch,NaN,red,left,blue,right,blueblack,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
3,76.0,NaN,10.0,sort,NaN,red,left,blue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
4,76.0,NaN,10.0,double,NaN,red,left,blueblue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN

In [107]:
d = dRaw.loc[ (dRaw['OUTPUT']!="0") & (dRaw['OUTPUT_SIDE'] != "0") ]

In [108]:
len(d), len(dRaw)

(107, 110)

In [109]:
d.head()

,ID,DOB,AGE,ALGO TYPE,DEMO,OUTPUT,OUTPUT_SIDE,OUTPUT.1,OUTPUT_SIDE.1,OUTPUT.2,...,OUTPUT.18,OUTPUT_SIDE.18,OUTPUT.19,OUTPUT_SIDE.19,OUTPUT.20,OUTPUT_SIDE.20,OUTPUT.21,OUTPUT_SIDE.21,NUMBER_MOVEMENTS,NOTES
0,74.0,NaN,12.0,sort,NaN,red,left,blue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
1,74.0,NaN,12.0,double,NaN,red,left,blue,right,redred,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN
2,74.0,NaN,12.0,hitch,NaN,red,left,blue,right,blueblack,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
3,76.0,NaN,10.0,sort,NaN,red,left,blue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
4,76.0,NaN,10.0,double,NaN,red,left,blueblue,right,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN

In [122]:
import warnings

def parseTsiData (data): 
    dataStr = []
    for i, row in d.iterrows():
        ID = row["ID"]
        algoType = row["ALGO TYPE"]
        age = row['AGE']
        iterRow = iter(row[5:-2])
        ri = 0
        overall_response_count = row["NUMBER_MOVEMENTS"]
        BallMovedCount = 0
        for outputCol in iterRow:
            ballMoved = outputCol
            side = next(iterRow)
            if (not pandas.isna(ballMoved)) & (not pandas.isna(side)):
                ri+=1
                for ai, ball in enumerate(re.findall(r"blue|black|red", ballMoved)):
                    BallMovedCount+=1
                    singleAct = [age, algoType, None, None, None, None, ID ,None,None,None,None,None,None, BallMovedCount, ri, ai, side, ball]
                    dataStr.append(singleAct)
        if overall_response_count != ri:
            print overall_response_count, ri
            warnings.warn("reported response count doesn't match actual number of response parsed at ID: {ID}, Algo: {Algo}".format(ID=ID, Algo=algoType))
    return dataStr

In [123]:
dataStr = parseTsiData(d)
finalDF = pandas.DataFrame(dataStr, columns=outputCSVHeaders)

7.0 15
10.0 7
10.0 14
12.0 10
12.0 13
10.0 11
14.0 12
10.0 12
9.0 12
23.0 22
14.0 13
11.0 9
20.0 19
12.0 14
nan 16
nan 12
nan 7
nan 22
nan 18
nan 9
nan 20
nan 16
nan 13
nan 10
nan 10
nan 6
nan 12
nan 11
nan 7
nan 0
nan 0
nan 0
nan 15
nan 15
nan 8
nan 15
nan 19
nan 10
nan 12
nan 19
nan 18
nan 13
nan 12
nan 18
nan 14
nan 13
nan 6
nan 16
nan 13
nan 11
nan 10
nan 16
nan 11
nan 10
nan 0
nan 11
nan 7
nan 9

/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 82.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 82.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 84.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 84.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 93.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 94.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 97.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 100.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 100.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 124.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: nan, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 127.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 129.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 129.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 134.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 134.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 134.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 135.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 135.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 135.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 138.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 138.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 138.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 139.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 139.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 139.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 145.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 145.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 145.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 152.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 152.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 152.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 163.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 163.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 163.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 164.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 164.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 164.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 171.0, Algo: randomsort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 171.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 171.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 171.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 173.0, Algo: randomsort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 173.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 173.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 173.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 174.0, Algo: match
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 174.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 174.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 174.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 176.0, Algo: randomsort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 176.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 176.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 176.0, Algo: hitch
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 183.0, Algo: randomsort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 183.0, Algo: sort
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 183.0, Algo: double
/Users/reese/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:24: UserWarning: reported response count doesn't match actual number of response parsed at ID: 183.0, Algo: hitch

In [124]:
finalDF.head()

,AGE,ALGOTYPE,DEMO,OVERALL.RESPONSE,KNOWERLEV,GENDER,ID,PASS_SORT,PASS_DOUBLE,PASS_HITCH,PASS_SORT_1,PASS_DOUBLE_1,PASS_HITCH_1,OVERALL.RESPONSE.NO,RESPONSE.NO,ACTION.NO,BUCKET,RESPONSE
0,12.0,sort,None,None,None,None,74.0,None,None,None,None,None,None,1,1,0,left,red
1,12.0,sort,None,None,None,None,74.0,None,None,None,None,None,None,2,2,0,right,blue
2,12.0,sort,None,None,None,None,74.0,None,None,None,None,None,None,3,3,0,left,red
3,12.0,sort,None,None,None,None,74.0,None,None,None,None,None,None,4,4,0,right,blue
4,12.0,sort,None,None,None,None,74.0,None,None,None,None,None,None,5,5,0,left,red

In [121]:
finalDF.to_csv("./experimentTsimaneData_newAlgo_withAge.csv")

In [80]:
newDF = finalDF.drop(columns=['ALGOTYPE', 'DEMO', 'OVERALL.RESPONSE', 'OVERALL.RESPONSE.NO', 'RESPONSE.NO', 'ACTION.NO', 'BUCKET', 'RESPONSE'])

In [83]:
newDF = newDF.drop_duplicates()
newDF.head()
# newDF.to_csv("./experimentData_CodingKL.csv")

In [87]:
finalDF['KL_AGE'] = finalDF['KNOWERLEV'].map(str) + "_" + finalDF['AGE'].map(str)
finalDF.head()

,AGE,ALGOTYPE,DEMO,OVERALL.RESPONSE,KNOWERLEV,GENDER,ID,PASS_SORT,PASS_DOUBLE,PASS_HITCH,PASS_SORT_1,PASS_DOUBLE_1,PASS_HITCH_1,OVERALL.RESPONSE.NO,RESPONSE.NO,ACTION.NO,BUCKET,RESPONSE,KL_AGE
0,4.821,SORT,"R/, /G, R/, /G, R/, /G, R/, /G","R/, /G, /RGxc, /G, R/, /G",5.0,FEMALE,4,1.0,1.0,1.0,1.0,1.0,1.0,0,0,0,left,R,5.0_4.821
1,4.821,SORT,"R/, /G, R/, /G, R/, /G, R/, /G","R/, /G, /RGxc, /G, R/, /G",5.0,FEMALE,4,1.0,1.0,1.0,1.0,1.0,1.0,1,1,0,right,G,5.0_4.821
2,4.821,SORT,"R/, /G, R/, /G, R/, /G, R/, /G","R/, /G, /RGxc, /G, R/, /G",5.0,FEMALE,4,1.0,1.0,1.0,1.0,1.0,1.0,2,2,0,left,G,5.0_4.821
3,4.821,SORT,"R/, /G, R/, /G, R/, /G, R/, /G","R/, /G, /RGxc, /G, R/, /G",5.0,FEMALE,4,1.0,1.0,1.0,1.0,1.0,1.0,3,2,0,right,R,5.0_4.821
4,4.821,SORT,"R/, /G, R/, /G, R/, /G, R/, /G","R/, /G, /RGxc, /G, R/, /G",5.0,FEMALE,4,1.0,1.0,1.0,1.0,1.0,1.0,4,3,0,right,G,5.0_4.821